add database migration
foxsheldin/my-favorite-movies-back pull request #1
Opened 2023-05-02 14:07 UTC by foxsheldin

2023-05-02 15:12 UTC, Isidora25 requested changes

2023-05-02 15:12 UTC, Isidora25 commented on src/movie/favorite-movie.entity.ts
> +  userId: string;
странный тип ты выбрал для уникального поля, тут либо автоинкремент для целого числа, либо UUID

2023-05-02 15:12 UTC, Isidora25 commented on src/movie/favorite-movie.entity.ts
> +  movie: number;
movieId?

2023-05-02 15:12 UTC, Isidora25 commented on src/movie/favorite-movie.entity.ts
> +  @Column({ type: 'numeric' })
а что за тип { type: 'numeric' } ? 
я такой не встречала, поэтому и спрашиваю

2023-05-02 15:12 UTC, Isidora25 commented on src/movie/favorite-movie.entity.ts
> +  isWatched: boolean;
а зачем имя меняешь?
почему не используешь одинаковое?

2023-05-03 11:29 UTC, Isidora25 approved these changes

2023-05-03 12:11 UTC, reshetov approved these changes

2023-05-03 12:11 UTC, merged