feat: add a service for interacting with an external API
foxsheldin/my-favorite-movies-back pull request #2
Opened 2023-05-10 14:07 UTC by foxsheldin

2023-05-11 08:07 UTC, reshetov requested changes

2023-05-11 08:07 UTC, reshetov commented on src/movie/favorite-movies.types.ts
> +  isFavorite: boolean;
А зачем этот флаг? Если фильм в избранных, он явно isFavorite

2023-05-11 08:07 UTC, reshetov commented on src/movie/movie.service.ts
> +      isFavorite: true,
Вот в продолжение вопроса выше

2023-05-11 08:07 UTC, reshetov commented on src/movie/movie.service.ts
> +    const favoriteMovieIds = await this.favoriteMovieRepository.findBy({
Тут у тебя судя по всему не ID возвращаются, а фильмы (судя по тому что ты их мапаешь ниже), тогда переменная называться должна по другому

2023-05-11 08:07 UTC, reshetov commented on src/movie/movie.service.ts
> +  async createFavoriteMovie(
Тут немного странное поведение, когда я вызывают createMovie я ожидают в ответ получить либо просто код 201 (created) либо этот фильм (данные по нему с id из базы). Но не как список ID избранных фильмов

2023-05-11 08:07 UTC, reshetov commented on src/movie/movie.service.ts
> +    await this.favoriteMovieRepository.create(movieDto).save();
А если он уже есть?

2023-05-11 08:07 UTC, reshetov commented on src/movie/movie.service.ts
> +    await this.favoriteMovieRepository.delete(movieDto);
Оно нормально отработает если фильма нет?

2023-05-11 08:07 UTC, reshetov commented on src/movie/movie.service.ts
> +  async getFavoriteMovieIds(userId: string): Promise<number[]> {
Тут не столько критично, но вообще в целом о безопастности не стоит забывать.
В твоем методе ЛЮБОЙ человек может отправить в запросе ЛЮБОЙ userId и получить данные по другому пользователю. Тоже самое с delete и update. По уму нужно ограничивать скоуп поиска данными текущего пользователя (или проверять что этот админ и может все).
На текущий момент у тебя еще нет авторизованного пользователя, но пометочку лучше себе оставить

2023-05-11 08:08 UTC, reshetov requested changes
Some comments

2023-05-15 15:18 UTC, foxsheldin commented on src/movie/favorite-movies.types.ts
> +  isFavorite: boolean;
Этот флаг нужен при запросе списка всех фильмов, так как при их просмотре не ясно где фильм уже находится в избранном
https://github.com/foxsheldin/my-favorite-movies-back/pull/2/files/a2e080ff3006ccda8670b239ecdb8672042aa1f6#diff-d4141e92d9db050533b6c2bdb85bce7bc689aabf6465873160bbd84ae6a92ca7R95

2023-05-16 07:35 UTC, reshetov commented on src/movie/favorite-movies.types.ts
> +  isFavorite: boolean;
Так если фильм в избранном мы знаем его ID, просто в ответе проверяй есть ли id фильма в массиве id избранных фильмов и если да - отмечай как уже выбранный.

2023-05-16 08:09 UTC, reshetov approved these changes

2023-05-16 09:28 UTC, Isidora25 requested changes

2023-05-16 09:28 UTC, Isidora25 commented on src/request-movies/request-movies.service.ts
> +    }
лучше использовать нестовский  Logger для логирования, он все красиво подсвечивает и легче дебажить 
https://docs.nestjs.com/techniques/logger#using-the-logger-for-application-logging

2023-05-16 10:18 UTC, Isidora25 approved these changes

2023-05-16 10:23 UTC, merged