feat: add GraphQL queries and mutations
foxsheldin/my-favorite-movies-back pull request #3
Opened 2023-05-17 09:10 UTC by foxsheldin

2023-05-19 10:24 UTC, Isidora25 requested changes

2023-05-19 10:24 UTC, Isidora25 commented on src/genre/genre.service.ts
> +    return this.requestMoviesService.getGenre(language);
await тут не нужен?

2023-05-19 10:24 UTC, Isidora25 commented on src/movie/dto/movie-filter.dto.ts
> +  selectedGenres?: number[];
```suggestion
  selectedGenresIds?: number[];
```

2023-05-19 10:24 UTC, Isidora25 commented on src/movie/movie.resolver.ts
> +  ): Promise<GetFavoriteMovieListOutput> {
GetFavoriteMovieListOutput используется и для AllMovies, и дляFavoriteMovieList
переименуй обобщенно

2023-05-19 10:24 UTC, Isidora25 commented on src/movie/movie.resolver.ts
> +  }
не очень понимаю, в чем разинца между запросами?

2023-05-19 10:24 UTC, Isidora25 commented on src/user/user.resolver.ts
> +  }
этот эедпойнт обычно называется signUp или register

2023-05-19 10:24 UTC, Isidora25 commented on src/user/user.service.ts
> +    const user = User.create({ username, password });
пароль в незашифрованном виде нельзя хранить в бд

2023-05-19 10:24 UTC, Isidora25 commented on src/user/user.service.ts
> +        'A user with such an email already exists!',
если username - это email, то лучше везде это переименовать в email и сделать дополнительую проверку, что это правда email, а не рандомная строка

если допускается любая строка, то тогда сообщени об ошибке неверное

2023-05-19 10:24 UTC, Isidora25 commented on src/user/user.service.ts
> +    const user = User.create({ username, password });
почему не через userRepository?

2023-05-19 11:50 UTC, foxsheldin commented on src/movie/movie.resolver.ts
> +  }
Запрос `getFavoriteMovieList` выдает список избранных фильмов, а `getAllMovies` - список всех фильмов, которые можно добавить себе в избранное. Я тогда поменяю названия функций для полной ясности

2023-05-19 11:50 UTC, foxsheldin commented on src/user/user.service.ts
> +    const user = User.create({ username, password });
Я планировал зашифровывать пароль при добавлении JWT авторизации

2023-05-19 11:58 UTC, foxsheldin commented on src/genre/genre.service.ts
> +    return this.requestMoviesService.getGenre(language);
Да, он там не нужен, так как имеется в этом месте
https://github.com/foxsheldin/my-favorite-movies-back/pull/3/files/d49a90b0246a42c797f4207bf912d67ee224bc94#diff-d4141e92d9db050533b6c2bdb85bce7bc689aabf6465873160bbd84ae6a92ca7R54

2023-05-19 13:21 UTC, Isidora25 approved these changes

2023-05-31 08:13 UTC, Isidora25 requested changes

2023-05-31 08:13 UTC, Isidora25 commented on src/auth/auth.service.ts
> +      throw new BadRequestException('Incorrect login or password');
сообщение об ошибке можно вынести в константу, так как оно повторяется

2023-05-31 08:13 UTC, Isidora25 commented on src/auth/auth.service.ts
> +    return this.userService.createUser({ email, password });
про await не забывай

2023-05-31 08:13 UTC, Isidora25 commented on src/user/user.service.ts
>      });
это больше часть процесса регистрации, чем создания записи в таблице

2023-05-31 10:05 UTC, Isidora25 approved these changes

2023-05-31 10:57 UTC, reshetov approved these changes

2023-05-31 10:57 UTC, merged